[google_service_account]
type = "service_account"
project_id = "my-project-27937-1696825693916"
private_key_id = "1471ed65b02dcedce7b4b28a5084ba58f2e5991e"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC2vA0FUvruQU64
AwIzxBoQgcahQ0m0ZZ9air3F4RdSIjSEqsLx94yI4COtOEh5mgpOvrzNpIPgfV4v
ZsXVrZbjdeFFyE430y1QoLeFUWUT0QfNqSYKo+A5MUA/w8XoiHDPm8sIXfZpd5RI
6EDR/jzGgzJjTAE8x1pCwTYnE75oCZDr3dhnVvLaMWUnV3x4bSjIqKY108gIeIw1
TP8o3NUvfDx1baRixTxIgRG5pbeRwh8/Z3nGwbP9YOvipnv2npUP5grPYQPdkL8O
epN/B5xoFd3I7g9gZcCUcywvakclM4ZIJEgpFG1bE7HoQZy+0P7M9unVaFDxZkZg
7+fxAV55AgMBAAECggEAAinn3ZBF+Fw9mmAuvn4r8NYYjABH9yLc6C2MYbNwm0Bc
btW2yTatK1G8Gmj4MrhoNtZ7VdQE27ugSd9lqEoN51OV/0WH55FQkAvXIHT+RWXM
Odsu4CFgnky+/gJLbZ1v+IVXuhmiuUz5LIPTgKkJ/y++gP59ZULXBsNS6NOLBaBS
OoGGdVNAjLdywVIyEjGziqwqAdkpJCyc6pDvPyRNckj4MoUnQC2qgjiG8B4DeU4+
nxQ1afsKx/dt858wFkAkcR6BYFE9ddR0FvuIa7mOzHKEpela9HUzaK/SifNYRNcY
xSsFAGT9N8GwuIQ8xNWo8HeUG0kbMaugqWiAFy1XoQKBgQDsenwIveBC9MWPTRS5
o+J9Q/6jFTn6htBUyc0/kmazZdmPoqyId7st9S8VsFXKK72tzReb02zbA+sIGAkb
73xjTvBt0wvg5KV2TlR8fB+2xfyQfX/1WKJgNGOY9Aem0fchWohzLEsKJWMR1HpT
R2nZDy/Nr28au2forY33qmbezwKBgQDF0csPYaRBD6YSTMBSiWZ37lQDyHaB2X2h
QfsxDA2wxOEyRRzlYC4eMqYOTEwafTP47WtqbJVBjIZpYf3NFED56jbE9jDr20G+
YUNRUW2plxuUaR6j/Se1hpUb4ln5/v3XpRnL8ZLAp4jhVB9GeT2nrcWZ4kY/2gLf
/4kIIoCANwKBgQCcaOsvEP+K6cDd5nrFyprchaOflEOT66VR32QNHzUkhUIgGdWK
Mb8xR5FMBCTKIqJDmXp7C51dQzsqUFN+EamxOZ4W1ddueWzjUi3ZZHPJfSxvGUMQ
MP69KQmTOhzxfsC5Y9sKaop7fH0JZwM9n+dntP7GSbnv8XJp2Jkk7aU6ywKBgHxK
UXRrnAFI7MZItPnm3Jv0AZOS62qwlS+xvjrV4PA0821bYUl5QeC1YAJRy+tEyVfZ
DImEic7ylS03ZXjqBd1AXIMqUBiQ3WDZyasZJ3bLu4dm+Np+X+m9Eoi/klrx7NoG
IQwzz0n+uZEiAriLysJE+4exVQQfXXkSHC4hR23HAoGAZDljlH/K0Cs8wEIdGXg9
2emOA6rhUUbuW1qOmjEL4imS6kcVi5EVsUWG9adCXKRHIQEmDPwmPf5a5aD+A6XN
9hxRxdI5l5kHtedplqWm3HoUTgYnNodg9jz3dxGknuO70Bpfcrk3L5PYTafgSnUs
VzJ9xN3GtfE+LQgim7k0hIg=
-----END PRIVATE KEY-----"""
client_email = "databpslabura@my-project-27937-1696825693916.iam.gserviceaccount.com"
client_id = "118240040324165473140"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/databpslabura%40my-project-27937-1696825693916.iam.gserviceaccount.com"
