[GOOGLE_SERVICE_ACCOUNT]
type = "service_account"
project_id = "desamembangmuda"
private_key_id = "875dc4c057baab982028fe1ed2cb8b91928dfc77"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCgQBE+eNSYSNcS
R9hTidXBh9Np1puSGOeJrecct5R0v/n39J1HWafYgLnD832poqE734xpUy/K8r7X
vMOh+YX14Z6KFtl0Y8uX1JjEMK44I4dtjZhiQzzQGcImCZFZ1Bo2u3rpt5SC3NXb
ARHPObqCMsvOUmYW+PPhxq7wAk04JMjj7Nk5Rspbkj5K+hjwWfW7He85vuCA9+0r
BJCblNogOt8m6ctlTIzBJvzaH55cHVEuCaEXEKY+L53g7EfJNaMpTE4LHzdjSbZ0
ZpSc+4s0ZrGVhQR0SfiS2/fdSEwf8NkyuTGr0rhJMJ2D4Fu/fy91yI9sn7vT+kuI
PhWzQmrzAgMBAAECggEAQqkkAzbESOzT+pjEVkvaDX1w5nANmwKdHlqm7v021jId
y5WH72xOM/OoUujw9yXdqEhf4lhmYygDVz8Aqlpf7V6DUrIalx4ETQ501ffiIRw2
c84Y+5c4ruBoMOZ9/j4LAYWPpbVmI+G1XDrfq7I58Xsr6JHCQgAhg2Pg1Zo/gQCz
KYpNTm3s3ABF7bP9CM7KqdiYdD4xrT3UDM3vs0YAy92pqRqp68jmpfJ3t2pPUi38
fOzxt5NdRwLz27BQns67+QTdPup91VVVBxrspn0CrlsM16XVY/mpwKFlcM591/83
f732SBo7CMrshPQcYY7QciRPfoC8S36gBqcEVESGoQKBgQDciRhKec8kJ3KxH/5A
SFhNR4hke0VgaO/TJL6lkRHOxw7B3uaBbBVrW8WSZEsPYp9XxzOSI7dznymLZtCn
NPuHGAV4882i0NmDnE+Rdq6CYCiQzQj1elqKgBvBd/IuepMOUNGkPBW8VAR4cXDc
SIQB4rVoIUjkxKvOCINeNMK4ywKBgQC6BS0tBmP+FExOemOyX6ousKp/mWU3yxxH
X76d+O+Yow0mQFQXv+hcK/UXgcZMCRYquudsriZs6bs0PRtEfJHAfrkN4tQ7FWKi
sq3cgSCupmbG7fu9JoeTPM8RPuSUisgdainnkIZIuUMoXBs8LTMDWLJ+F1VPtHly
PL9dfB/ZeQKBgQCXtcf8E+enm2uO5c9mMV5tazQsy5BiTk4NFk4AX9e8Q7unKsuv
ZMcnX65+kngAUXwESojzk5Zz954Aw+3t2MjfmmrJVg60XrADldg23UoXbkb5tdLf
7Be1B4QQh48W4kOfqYFOVfct4y5gHMnjAA+vrGHXDG600YbO6ZRVjj4WGQKBgEKN
TY9ZRPcHHhHJudd8YG+Z5zYFlG/0q+ZhO9pa0KXEWBUCWNOyZhhr5aEGXgKgEZ0y
B1AbskWvDbnvzsye4KqE7AIq0BFfYk2hLZDBZgb2I7kyNamDmme0DsU1wiPezx+u
9tURIOnt1jgfU+MgrKqa1ilEgdIlWHnlf/WbTe3JAoGBAJfoN5WP4gXPhDKuyoY4
V5oBF2Qr1502ahA0/jT9+kLmDylzC5KOlaBbxB4HkwyqQ1XUKYMVfQTRenpih2U7
hM2y+wzI9fr7aTjVjXimnmg/9VcQtP2c6X+m5X8R4a3paKRrc/aWWi0+dypsnPoG
SzZ7va2apjCMLkUvMwqTgkHq
-----END PRIVATE KEY-----"""
client_email = "desa1223@desamembangmuda.iam.gserviceaccount.com"
client_id = "118186806263993508789"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/desa1223%40desamembangmuda.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
