[GOOGLE_SERVICE_ACCOUNT]
type = "service_account"
project_id = "desamembangmuda"
private_key_id = "fc3581f0645e6710f8dc15499da9134ef9cdcccf"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQD2oDg2iWjhqtJw
QsDD64hMK4Fll0gGERatq3nk79HvQlBnqZS2YjtVnWqVFRk0FIH+RpCdx9Sb29O9
h8Y5jOELZlTTnYhbNr22p8hz2dWKptrGxxTGy2u2YJEmRk7VTBock09MJmaMgb6v
V/wmTQnE1HdQzcq1kWGDsjOXjJOyqRc4vMgFgsa6c5Pag+mS/fIvKeXp7VzK+gkA
WtFPS8tO+dxC8Jzh9Ay69Q1di0A03F3PAagxExhXthW0VUSNifoNAQJ005qKOAUm
MAB8+M0UxvVwftvMaw1KevqNCgSHZLIlYOoAZv34RKXPAjPLcyknxQlgCbYXHeDn
RoXp0KHtAgMBAAECggEASqNun8KyRSmnimYJZMHRfAvmm1JPb9aYIHM27rxNsrVF
FDpUUWYlQuHjMb8y43oZZVUBy16Az7KVwFRo/13Ndd/AaFLSw5grji31Emqon8+j
gmkZtpg1vvo2s3ivvwnLFT7XztoISxmxFevw2b6S6EjM212MraqT8oFp78GRqY2+
6GNtgOV035WroRTcrzfUt1TwCJc1zGP/t5Hck4dYnR/Engl+3kBWFTtvRe6oPdGp
lSggEoXhI/rFbe006RbtBajfZkpNXGEwZdgw8p1iC1JMukW46eC3aiH2tC1mGlU4
LIVAKX+7L+4cHG/Rxf9Dtvrtrj94RLZ3iYCEBsTYmQKBgQD+6yT+ARjN3/upvYEw
8/rRsGlohhAWEiC9EKHdfTo0279EfAcxnXqLv7IxZToJlFdFnIBYyk7ffn8Yt9hc
6ob2bPLE976dJqo68BM+E7/NhuAbDshbxt5DPisGnDoKW/6d34xU9EwDX7e+cDgQ
XGvT0l9Pjwu+2JStw8ji2FuVVwKBgQD3rBGbppEVapUYQm9ZwLFzk4LT5lbh2FhG
i/tLDglGDvYcacXCAbQSc02/EPHnp7KPp7SjjCwGic+v6/VlHbWEsF8g3xOm5v4z
cVk0yJog+YRYX6ryIDiKZ61P8Nza3DwzsSxrWPtLwqMAEUUxOIwS76ey1NLS0WjZ
7MooEo5UWwKBgQDLMoT6M8Wh1bi1ROmGK/Ty0Lw1JSgNb8XI70kXVIrhN4ju/i59
zhmw680OsrHgkO4//tAP9rOIUzzcZy+AYTHTnGSnvROkEP4AnP25reRl3+0jpFTx
U0Q4NYX2bvGU8F+1WEx0K4er6NB+bNVDtWf+IOL4d/3U0q8xE689o1jdYQKBgHgN
IO/YumSuKBz9Puo7fAhwzS6XbS/F5Ww0uBc2c4pRADzfjGsw1i9HUr01onxOjkAR
436PGFwG+vPkJSvhTbZGo6XUW7tAJqGa5MmwHv2y1NLddIgu1BlKjfi84OD5dfj8
fXJ/TDf53XbP6EEmjsczAY+ul4520SMpIwhvjiwXAoGAes8XjYPto7+QT3SzQlbP
F+FnV0sntfNe0oSudmno4XIc1G8ScVOlMpupRf4b22Vpz0rh2hqbMaXObX4MRd6e
JyjdfZs39PaVYIQC2IFwlorhhyF2flkM2ecV23+G4q9ah67P2YNcNFXKAT5iS7lo
kg5lFTk23VPOlXK4qpDitXY=
-----END PRIVATE KEY-----"""
client_email = "desa1223@desamembangmuda.iam.gserviceaccount.com"
client_id = "118186806263993508789"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/desa1223%40desamembangmuda.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
